version: '3.1'
services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
    - HOST=db
    - USER=${POSTGRES_USER}
    - PASSWORD=${POSTGRES_PASSWORD}
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/newpgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/newpgdata
volumes:
  odoo-web-data:
  postgres-data:
